name: Main Workflow

on:
  push:
    branches:
      - main
      - master
      - develop
      - 'releases/**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install SonarQube Scanner
        run: |
          Invoke-WebRequest -Uri https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747.zip -OutFile sonar-scanner.zip
          Expand-Archive -Path sonar-scanner.zip -DestinationPath $env:USERPROFILE
          $env:PATH += ";$env:USERPROFILE\sonar-scanner-4.7.0.2747\bin"
        shell: pwsh

      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          $scannerPath = "${env:USERPROFILE}\sonar-scanner-4.7.0.2747\bin\sonar-scanner.bat"
          & $scannerPath `
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} `
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} `
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        shell: pwsh
